### ISSUE TITLE
Beginning of Wiki

### ISSUE THREAD

**Issue by Cocatrix** [Cocatrix/git-formation-mobile#5]
@Saryx11 Do you want to begin the wiki ?
(Like how to protect the master branch)

**Comment by Saryx11** [comment]
Done !

**Comment by Cocatrix** [comment]
Great, but could you add some pictures ?

**Comment by Saryx11** [comment]
lol nope !

Well, ok i'll try !

**Comment by Saryx11** [comment]
I did a new page with an image

**Comment by Cocatrix** [comment]
Just a link is missing on the homepage to go to the "protect master" wikipage. Thanks :)

**Comment by Saryx11** [comment]
Done with ease !
